apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.mysqlUser }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.mysql.mysqlPassword }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.mysqlDatabase }}
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: wordpress

